---
- name: Remediate
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    remediation_todo:
      - leapp_firewalld_allowzonedrifting
      - leapp_missing_pkg
  tasks:
    - name: Install vdo package
      ansible.builtin.package:
        name: vdo
        state: present
    
    - name: AllowZoneDrifiting is removed in RHEL9
      ansible.builtin.replace:
        path: /etc/firewalld/firewalld.conf
        regexp: '^AllowZoneDrifting=.*$'
        replace: "AllowZoneDrifting=no"

    - name: Although bad practice, if PermitRootLogin yes is set, add a comment to it
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes$'
        replace: "PermitRootLogin yes # root login required"
        
    - name: Perform remediations on the system
      ansible.builtin.import_role:
        name: infra.leapp.remediate
...
